### ISSUE TITLE
YoloV3 analyser in CPU build

### ISSUE THREAD

**Issue by breezykermo** [forensic-architecture/mtriage#120]
When running `./mtriage run yolov3.yaml` in the wiki tutorial via the CPU build of mtriage, it doesn't work. This is probably because it was developed on the GPU build specifically, and somewhere in the code things go whack.

**Comment by ivansafrin** [comment]
This issue is due to docker not allocating enough shared memory. Made a note of this in the wiki here:

https://github.com/forensic-architecture/mtriage/wiki/Common-issues
