### ISSUE TITLE
Rewrite run.py using docker python module

### ISSUE THREAD

**Issue by breezykermo** [forensic-architecture/mtriage#19]
Currently run.py uses the docker python module only very slimly, and essentially just templates the right bash command.

The original intention of using a Python script here rather than a bash script was so that the command could be run on Windows as well. Maybe we need to rethink this.

**Comment by breezykermo** [comment]
After looking into this a little, I'm not sure that it is the right direction.

One of the issues is that, for processes with more sophisticated output such as [pytest](https://docs.pytest.org/en/latest/) we lose a lot of the CLI output niceties like colours unless we write STDIN/STDOUT/piping logic.

I'm thinking it may actually just be better to assume that the user is using a Docker-saturated bash environment.

Thoughts @samludford @scztt ?

**Comment by scztt** [comment]
Naively, ansi should work via `Popen` and `call` and other variants:
```
import subprocess
subprocess.call('echo -e "\033[1;31m This is red text \033[0m"', shell=True)
```
Probably, pytest is detecting that there's no terminal present and is skipping color - looks like you can force it, maybe that's enough?
https://stackoverflow.com/a/24450942/981347
