### ISSUE TITLE
more sophisticated way to specify selector/analyser workflows

### ISSUE THREAD

**Issue by breezykermo** [forensic-architecture/mtriage#25]
mtriage is currently triggered through shell scripts that take similar arguments via argparse (loosely enforced, i.e. see #5).

We need a more elegant way to specify selector/analyser workloads, probably via subcommand architecture using something like [click](https://click.palletsprojects.com/en/7.x/).

Base spec for this:
- [x] the run.py should be made an executable python file, so that mtriage can be invoked via `mtriage --args`.
- [x] refactor run.py so that you don't need to TTY into the docker container via `python run.py develop`. There should be two entrypoints, `mtriage select --args` and `mtriage analyse --args`.
- [ ] the default `mtriage` command triggers a CLI interactive interface where you can select from available selectors/analysers, and input options as relevant to components as they are chosen. This should just be a prototype, not necessarily formalising interaction in future releases.

Extras for experts
- [x] Save a YAML file from the interactive CLI
- [ ] Clean way to link select and analyse runs together, so that mtriage can be run end-to-end.
- [x] Code in special cases for meta-analysers, i.e. a prompt to add another analyser after creating one.
- [ ] Work out how spinning up/out viewers fits into the workflow.

The interactive CLI will depend in part on the type system implemented in #66, using it to determine the composability of selectors, analysers, and viewers (modules) that input and output elements of different types.

**Comment by breezykermo** [comment]
Another thought on this: perhaps it would be nice to have meta-Analysers, i.e., a class that can be invoked as an analyser from mtriage's entry point, but which actually just consists of a set of analysers  applied in sequence. 

In pseudocode:
```python
class VideoVisionYolo(MetaAnalyser):
    def workflow():
        return [
            { "analyser": "frames", "options" {} },
            { "analyser": "pytorch", "options": { "path": "path/to/yolomodel" } }
        ]
```

@scztt, do you think this works as a way to encapsulate the audio analysis workflow we talked about offline?

**Comment by breezykermo** [comment]
Base spec for this:
- [ ] the run.py should be made an executable python file, so that mtriage can be invoked via `mtriage --args`.
- [ ] refactor run.py so that you don't need to TTY into the docker container via `python run.py develop`. There should be two entrypoints, `mtriage select --args` and `mtriage analyse --args`.
- [ ] the default `mtriage` command triggers a CLI interactive interface where you can select from available selectors/analysers, and input options as relevant to components as they are chosen. This should just be a prototype, not necessarily formalising interaction in future releases.

**Comment by samludford** [comment]
This issue has been addressed in a separate command line application: [https://github.com/forensic-architecture/mtriage-cli](https://github.com/forensic-architecture/mtriage-cli)
