### ISSUE TITLE
Update code to work with newest version of pandas

### ISSUE THREAD

**Issue by samludford** [forensic-architecture/mtriage#40]
Currently running the YoutubeSelector (via e.g. script `1.select.sh`) raises an error when using the newest version of pandas. 

Pandas has been pinned to version 0.18 as a workaround to this issue, but this is not ideal. All selectors should work with the most recent version.

**Comment by breezykermo** [comment]
Note: we are now aiming to drop Pandas as a dependency via #61, which would invalidate this.
