### ISSUE TITLE
add optionality to run selectors/analysers on GCP

### ISSUE THREAD

**Issue by breezykermo** [forensic-architecture/mtriage#6]
this is fundamentally necessary so that MT can be run in the cloud without exhausting resources on a DO droplet or similarly contained instance.

When the 'cloud' flag for a selector or analyser is specified, the following should occur:
* all raw data from the select pass should be saved in GCP buckets
* all derived data should read from and write to GCP buckets.
* there should be a boolean to switch between using GCP buckets and the local machine (we should definitely still support local file system so that google is not necessary to run).
* ideally storage is abstracted as an interface so that other providers could also be used in the future.

**Comment by JonathanReiss15** [comment]
Is there any specific reasoning behind choosing GCP over S3? I would propose that mtriage use S3 as there are multiple providers (AWS, DigitalOcean, Vultr, etc.) that provide S3 compatible services, while GCP buckets are GCP specific.

**Comment by breezykermo** [comment]
With #144, this is now supported in theory (documentation and more robust support is forthcoming).
