### ISSUE TITLE
Add viewer plugin functionality

### ISSUE THREAD

**Issue by samludford** [forensic-architecture/mtriage#60]
Users should be able to create their own viewer plugins: webpages which visualise the output of an analyser. mtriage should provide a standard interface for running viewers via the command line (as with selectors and analysers). Viewable derived elements should have a standardised json format which can be consumed by viewers.

**Comment by breezykermo** [comment]
A couple of comments towards this:
* it might be interesting to see if we can leverage [netlify-dev](https://www.netlify.com/blog/2019/04/09/netlify-dev--our-entire-platform-right-on-your-laptop/) to deal with some of the build complexity of frontend applications.
* I don't think viewable elements should have a fully standardised JSON format, but what should be standardised is what kind of elements viewers can accept. For example, I don't think it's unreasonable to assert that only elements with a single JSON file in them can be networked by a viewer, and that this JSON object should have certain attributes such as `id`.
* The viewer plugin functionality should make certain elements available to the frontend across the local network. This means that it should probably spin up an server that serves certain JSONs via HTTP request, using some sort of [static file server](https://www.alexedwards.net/blog/serving-static-sites-with-go). The most efficient way to do this might be to create a folder that creates symlinks to the relevant element directories, and then serves the directory that contains the symlinks (presuming you can statically serve symlinked files, which I think you should be able to).

**Comment by breezykermo** [comment]
closed by #64
