### ISSUE TITLE
use only f strings for string interpolation

### ISSUE THREAD

**Issue by breezykermo** [forensic-architecture/mtriage#8]
The method of string interpolation should be standardised to [f strings](https://realpython.com/python-f-strings/), as this is a Python 3 repo.

There was a point at which some of the scripts were confused between Python 2 and 3, which is partly why we have a range of interpolation methods.

**Comment by cuichenli** [comment]
Hey I am a first-timer looking for tasks to do. I found you may want some help on this issue. Could I jump in and help with it?

**Comment by breezykermo** [comment]
Hi @cuichenli, we'd welcome a PR for this issue! It basically consists of taking a look through the codebase for any instances of string interpolation that are _not_ f strings, and changing them to f strings.

If you're new to making PRs or want help getting started, join [our public channel on Keybase](https://keybase.io/team/fa_open_source) and we can help you get up and running. :-)
